---
- name: Configurar httpd como Proxy Reverso en Ubuntu
  hosts: ubuntu
  user: ansible
  become: true
  vars: 
   http_conf: 000-default.conf
 
  tasks:
    - name: Instalar Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Habilitar los módulos necesarios
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy
        - proxy_http

    - name: Configurar el archivo de sitio para el proxy reverso
      template:
        src: httpd_proxy.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify: Reiniciar apache2

    - name: Enable site
      ansible.builtin.command: 
        cmd: a2ensite "{{ http_conf }}"
      notify: Reiniciar apache2

  handlers:
    - name: Reiniciar apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted


    - name: Instalar UFW      
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Permitir tráfico en los puertos 80 y 443
      community.general.ufw:        
        rule: allow        
        port: "{{ item }}"        
        proto: tcp      
      loop:        
        - 80        
        - 443
        - 22

    - name: Habilitar UFW
      community.general.ufw:        
        state: enabled
